name: Download Gem from GitHub Packages

on:
  push:
    branches:
    - download-packages

jobs:
  download-via-gem:
    runs-on: ubuntu-latest

    permissions:
      packages: read

    steps:
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.8
      - run: gem --version
      - name: Download published gem
        env:
          GEM_HOST_API_KEY: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p pkg
          gem fetch equilibrium --version 0.2.0 \
            --source https://rubygems.pkg.github.com/${{ github.repository_owner }} \
            --clear-sources \
            --verbose
          mv equilibrium-*.gem pkg/


      # - name: Download gem via download
      #   run: |
      #     gem install equilibrium --source https://rubygems.pkg.github.com/TonyCTHsu --verbose


  download-via-bundler:
    runs-on: ubuntu-latest

    permissions:
      packages: read

    steps:
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.8
      - run: bundle --version
      - name: Configure bundler for GitHub Packages
        run: |
          bundle config https://rubygems.pkg.github.com/TonyCTHsu ${{ secrets.GITHUB_TOKEN }}
          bundle config list

      - name: Create temporary Gemfile
        run: |
          cat > Gemfile << 'EOF'
          source 'https://rubygems.org'
          source 'https://rubygems.pkg.github.com/TonyCTHsu' do
            gem 'equilibrium'
          end
          EOF

      - name: Download gem via bundler
        run: |
          bundle install --verbose
          bundle show equilibrium
