name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  release-gem:
    name: Release Gem
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'

    permissions:
      contents: write
      id-token: write
      packages: write

    environment: release

    outputs:
      version: ${{ steps.version.outputs.number }}

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Get version from gemspec
        id: version
        run: |
          VERSION=$(ruby -e "spec = Gem::Specification.load('equilibrium.gemspec'); puts spec.version")
          echo "number=$VERSION" >> $GITHUB_OUTPUT

      - name: Validate tag matches version
        run: |
          TAG_VERSION=${GITHUB_REF_NAME#v}
          GEMSPEC_VERSION=${{ steps.version.outputs.number }}
          if [ "$TAG_VERSION" != "$GEMSPEC_VERSION" ]; then
            echo "Error: Tag version ($TAG_VERSION) does not match gemspec version ($GEMSPEC_VERSION)"
            exit 1
          fi
          echo "Tag version matches gemspec version: $GEMSPEC_VERSION"

      - name: Publish to RubyGems
        uses: rubygems/release-gem@v1

      - name: Publish to GitHub Packages
        env:
          GEM_HOST_API_KEY: ${{ secrets.GITHUB_TOKEN }}
        run: gem push --host https://rubygems.pkg.github.com/TonyCTHsu pkg/*.gem

      - name: Get Changelog Entry
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v2
        with:
          version: ${{ steps.version.outputs.number }}
          path: ./CHANGELOG.md

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ steps.version.outputs.number }}
          tag_name: ${{ github.ref_name }}
          body: ${{ steps.changelog_reader.outputs.changes }}
          files: |
            pkg/*.gem

  release-docker:
    name: Release Docker Image
    runs-on: ubuntu-latest
    needs: release-gem

    permissions:
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version

      - name: Download published gem
        run: |
          mkdir -p pkg
          gem fetch equilibrium --version ${{ needs.release-gem.outputs.version }} --verbose
          mv equilibrium-*.gem pkg/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern=v{{version}}
            type=semver,pattern=v{{major}}.{{minor}}
            type=semver,pattern=v{{major}}
            type=raw,value=latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max