name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'

    permissions:
      contents: write
      id-token: write
      packages: write

    environment: release

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Get version from gemspec
        id: version
        run: |
          VERSION=$(ruby -e "spec = Gem::Specification.load('equilibrium.gemspec'); puts spec.version")
          echo "number=$VERSION" >> $GITHUB_OUTPUT

      - name: Validate tag matches version
        run: |
          TAG_VERSION=${GITHUB_REF_NAME#v}
          GEMSPEC_VERSION=${{ steps.version.outputs.number }}
          if [ "$TAG_VERSION" != "$GEMSPEC_VERSION" ]; then
            echo "Error: Tag version ($TAG_VERSION) does not match gemspec version ($GEMSPEC_VERSION)"
            exit 1
          fi
          echo "Tag version matches gemspec version: $GEMSPEC_VERSION"

      - name: Publish to RubyGems
        uses: rubygems/release-gem@v1

      - name: Publish to GitHub Packages
        env:
          GEM_HOST_API_KEY: ${{ secrets.GITHUB_TOKEN }}
        run: gem push --host https://rubygems.pkg.github.com/TonyCTHsu pkg/*.gem

      - name: Get Changelog Entry
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v2
        with:
          version: ${{ steps.version.outputs.number }}
          path: ./CHANGELOG.md

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ steps.version.outputs.number }}
          tag_name: ${{ github.ref_name }}

          body: ${{ steps.changelog_reader.outputs.changes }}
          files: |
            pkg/*.gem
